name: GitHub CI

on:
  push:
      branches:
        - 'main'
  pull_request:
      branches:
        - '**'

jobs:
  test:
    runs-on: ununtu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node JS
        uses: actions/setup-node@v3    
      - name: Install dependencies
        working-directory: ./Homework_14
        run: npm install
      - name: Test runner
        working-directory: ./Homework_14
        run: npm run test